image: maven:3-openjdk-11

clone:
  depth: full

pipelines:
  branches:
    development:
      - step:
          name: Build and Push Image
          script:
            - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
            - docker build -t tfhub/api-gateway:dev .
            - docker push tfhub/api-gateway:dev
    master:
      - step:
          name: Build and Push Image
          script:
            - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
            - docker build -t tfhub/api-gateway:latest .
            - docker push tfhub/api-gateway:latest
     # - step:
         # name: SonarQube analysis
          #caches:
           # - maven
          #  - sonar
         # script:
          #  - mvn verify -DskipTests=true -Dmaven.test.failure.ignore=true sonar:sonar
options:
  docker: true

#definitions:
  #caches:
   # sonar: ~/.sonar