version: '3'

services:
  api-gateway:
    build: .
    image: bdotransact/development-api-gateway
    container_name: development-api-gateway
    env_file:
      - /opt/config/development.env
    ports:
      - "3334:3333"

networks:
  default:
    external:
      name: development