version: '3'

services:
  api-gateway:
    image: bdotransact/api-gateway
    container_name: api-gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=staging"
    ports:
      - "3333:3333"

networks:
  default:
    external:
      name: staging