version: '3'

services:
  api-gateway:
    build: .
    image: bdotransact/api-gateway
    container_name: api-gateway
    env_file:
      - ./opt/config/staging.env
    environment:
      - "SPRING_PROFILES_ACTIVE=${PROFILE}"
    ports:
      - "3333:3333"

networks:
  default:
    external:
      name: staging