server:
  port: 3333

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://localhost:4444/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      defaultFilters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
      - id: dashboard-service
        uri: lb://dashboard-service
        predicates:
        - Path=/dashboard/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: administration-service
        uri: lb://administration-service
        predicates:
        - Path=/administration/groups/**,/administration/users/**
      - id: device-service
        uri: lb://device-service
        predicates:
        - Path=/device/**
      - id: transaction-service
        uri: lb://transaction-service
        predicates:
        - Path=/transaction/**
      - id: bin-service
        uri: lb://bin-service
        predicates:
        - Path=/bin/card-type/**,/bin/currency-code/**,/bin/bin-range/**
      - id: network-service
        uri: lb://network-service
        predicates:
        - Path=/network/acquiring/**,/network/issuing/**
      - id: monitoring-service
        uri: lb://monitoring-service
        predicates:
        - Path=/**
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  main:
    banner-mode: off