server:
  port: 3333

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:4444/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      defaultFilters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
      - id: dashboard-service
        uri: lb://dashboard-service
        predicates:
        - Path=/dashboard/**
      - id: user-settings-service
        uri: lb://user-settings-service
        predicates:
        - Path=/user-settings/**
      - id: system-administration-service
        uri: lb://system-administration-service
        predicates:
        - Path=/administration-groups/{segment},/administration-users/{segment}
      - id: monitoring-service
        uri: lb://monitoring-service
        predicates:
        - Path=/**
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
