server:
  port: 3333

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://localhost:4444/eureka/

cors:
  urls: http://localhost:3000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      defaultFilters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "${cors.urls}"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
      - id: dashboard-service
        uri: lb://dashboard-service
        predicates:
        - Path=/dashboard/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: administration-service
        uri: lb://administration-service
        predicates:
        - Path=/administration/**
      - id: device-service
        uri: lb://device-service
        predicates:
        - Path=/device/**
      - id: merchant-service
        uri: lb://merchant-service
        predicates:
        - Path=/merchant/**
      - id: card-account-service
        uri: lb://card-account-service
        predicates:
        - Path=/card-account/**
      - id: transaction-service
        uri: lb://transaction-service
        predicates:
        - Path=/transaction/**
      - id: bin-service
        uri: lb://bin-service
        predicates:
        - Path=/bin/card-type/**,/bin/currency-code/**,/bin/bin-range/**
      - id: network-service
        uri: lb://network-service
        predicates:
        - Path=/network/acquiring/**,/network/issuing/**
      - id: websocket-server
        uri: lb://websocket-server
        predicates:
        - Path=/**
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
      - id: authorization-service
        uri: lb://authorization-service
        predicates:
        - Path=/authorization/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  main:
    banner-mode: off